// chatbot/scripts/templates/angular/navigation.ts
import type { ComponentTemplate } from '../../generate-dataset';

const templates: ComponentTemplate[] = [
  {
    variant: 'breadcrumb',
    description: 'Breadcrumb navigation showing current page path',
    tags: ['navigation', 'breadcrumb', 'path'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-breadcrumb-nav',
  template: \`<nav class="breadcrumb"><span *ngFor="let crumb of crumbs; let i = index; let last = last"><span *ngIf="i > 0" class="sep">/</span><a *ngIf="!last" [href]="crumb.href" class="link">{{ crumb.label }}</a><span *ngIf="last" class="current">{{ crumb.label }}</span></span></nav>\`,
  styles: [\`.breadcrumb { display: flex; align-items: center; gap: 4px; font-size: 14px; padding: 12px 0; } .sep { color: #9ca3af; margin: 0 4px; } .link { color: #6366f1; text-decoration: none; } .current { color: #374151; font-weight: 600; }\`]
})
export class BreadcrumbNavComponent { crumbs = [{ label: 'Home', href: '#' }, { label: 'Products', href: '#products' }, { label: 'Widget Pro', href: '' }]; }

@NgModule({ declarations: [BreadcrumbNavComponent], imports: [BrowserModule], bootstrap: [BreadcrumbNavComponent] })
export class BreadcrumbNavModule {}
export default createAngularMicroApp({ name: 'breadcrumb-nav', module: BreadcrumbNavModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'tabs',
    description: 'Tab navigation with active state and content switching',
    tags: ['navigation', 'tabs', 'switch'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-tabs-nav',
  template: \`<div class="tabs"><button *ngFor="let tab of tabs" class="tab" [class.active]="active===tab" (click)="active=tab">{{ tab }}</button></div><div class="content">Content for {{ active }}</div>\`,
  styles: [\`.tabs { display: flex; gap: 0; border-bottom: 2px solid #e5e7eb; } .tab { padding: 10px 20px; background: none; border: none; border-bottom: 2px solid transparent; margin-bottom: -2px; cursor: pointer; font-size: 14px; font-weight: 500; color: #6b7280; } .tab.active { border-bottom-color: #6366f1; color: #6366f1; font-weight: 600; } .content { padding: 20px 0; font-size: 14px; color: #6b7280; }\`]
})
export class TabsNavComponent { active = 'Overview'; tabs = ['Overview', 'Features', 'Pricing', 'Reviews']; }

@NgModule({ declarations: [TabsNavComponent], imports: [BrowserModule], bootstrap: [TabsNavComponent] })
export class TabsNavModule {}
export default createAngularMicroApp({ name: 'tabs-nav', module: TabsNavModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'stepper',
    description: 'Step-by-step progress navigation with numbered steps',
    tags: ['navigation', 'stepper', 'progress'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-stepper-nav',
  template: \`<div class="stepper"><div *ngFor="let step of steps; let i = index" class="step" [class.active]="i <= current" [class.done]="i < current"><div class="circle">{{ i < current ? '\\u2713' : i + 1 }}</div><span class="label">{{ step }}</span></div></div><div class="actions"><button [disabled]="current===0" (click)="current=current-1">Back</button><button [disabled]="current===steps.length-1" (click)="current=current+1">Next</button></div>\`,
  styles: [\`.stepper { display: flex; align-items: center; gap: 8px; padding: 20px 0; } .step { display: flex; align-items: center; gap: 8px; } .step::after { content: ''; width: 40px; height: 2px; background: #e5e7eb; } .step:last-child::after { display: none; } .step.active::after { background: #6366f1; } .circle { width: 32px; height: 32px; border-radius: 50%; border: 2px solid #d1d5db; display: flex; align-items: center; justify-content: center; font-size: 13px; font-weight: 600; } .step.active .circle { border-color: #6366f1; color: #6366f1; } .step.done .circle { background: #6366f1; color: #fff; border-color: #6366f1; } .label { font-size: 13px; color: #6b7280; } .step.active .label { color: #6366f1; font-weight: 600; } .actions { display: flex; gap: 8px; padding: 16px 0; } .actions button { padding: 8px 20px; border: 1px solid #d1d5db; border-radius: 6px; background: #fff; cursor: pointer; } .actions button:disabled { opacity: 0.4; }\`]
})
export class StepperNavComponent { current = 0; steps = ['Account', 'Profile', 'Payment', 'Confirm']; }

@NgModule({ declarations: [StepperNavComponent], imports: [BrowserModule], bootstrap: [StepperNavComponent] })
export class StepperNavModule {}
export default createAngularMicroApp({ name: 'stepper-nav', module: StepperNavModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'pagination',
    description: 'Pagination navigation with page numbers and prev/next',
    tags: ['navigation', 'pagination', 'pages'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-pagination-nav',
  template: \`<nav class="pagination"><button [disabled]="page===1" (click)="page=page-1">\\u2190 Prev</button><button *ngFor="let p of pages" class="page-btn" [class.active]="page===p" (click)="page=p">{{ p }}</button><button [disabled]="page===totalPages" (click)="page=page+1">Next \\u2192</button></nav>\`,
  styles: [\`.pagination { display: flex; align-items: center; gap: 4px; } button { padding: 8px 14px; border: 1px solid #d1d5db; border-radius: 6px; background: #fff; cursor: pointer; font-size: 13px; } button:disabled { opacity: 0.4; cursor: default; } .page-btn.active { background: #6366f1; color: #fff; border-color: #6366f1; }\`]
})
export class PaginationNavComponent {
  page = 1; totalPages = 5;
  get pages() { return Array.from({ length: this.totalPages }, (_, i) => i + 1); }
}

@NgModule({ declarations: [PaginationNavComponent], imports: [BrowserModule], bootstrap: [PaginationNavComponent] })
export class PaginationNavModule {}
export default createAngularMicroApp({ name: 'pagination-nav', module: PaginationNavModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'menu',
    description: 'Dropdown menu navigation with hover reveal',
    tags: ['navigation', 'menu', 'dropdown'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-menu-nav',
  template: \`<div class="menu-container"><button class="trigger" (click)="open=!open">Menu \\u25BC</button><div class="menu" *ngIf="open"><a *ngFor="let item of items" [href]="'#' + item.toLowerCase()" class="menu-item" (click)="open=false">{{ item }}</a></div></div>\`,
  styles: [\`.menu-container { position: relative; display: inline-block; } .trigger { padding: 10px 20px; background: #fff; border: 1px solid #d1d5db; border-radius: 6px; cursor: pointer; font-size: 14px; } .menu { position: absolute; top: 100%; left: 0; margin-top: 4px; background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; min-width: 180px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); z-index: 10; padding: 4px 0; } .menu-item { display: block; padding: 10px 16px; text-decoration: none; color: #374151; font-size: 14px; } .menu-item:hover { background: #f3f4f6; }\`]
})
export class MenuNavComponent { open = false; items = ['Dashboard', 'Profile', 'Settings', 'Help', 'Log Out']; }

@NgModule({ declarations: [MenuNavComponent], imports: [BrowserModule], bootstrap: [MenuNavComponent] })
export class MenuNavModule {}
export default createAngularMicroApp({ name: 'menu-nav', module: MenuNavModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'navbar',
    description: 'Horizontal navigation bar with links and active state',
    tags: ['navigation', 'navbar', 'horizontal'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-navbar',
  template: \`<nav class="navbar"><a *ngFor="let link of links" [href]="'#' + link.toLowerCase()" class="link" [class.active]="active===link" (click)="active=link">{{ link }}</a></nav>\`,
  styles: [\`.navbar { display: flex; gap: 8px; padding: 8px; background: #f9fafb; border-radius: 8px; } .link { padding: 8px 16px; text-decoration: none; color: #6b7280; border-radius: 6px; font-size: 14px; font-weight: 500; } .link:hover { background: #e5e7eb; } .link.active { background: #6366f1; color: #fff; }\`]
})
export class NavbarComponent { active = 'Home'; links = ['Home', 'Products', 'About', 'Contact']; }

@NgModule({ declarations: [NavbarComponent], imports: [BrowserModule], bootstrap: [NavbarComponent] })
export class NavbarModule {}
export default createAngularMicroApp({ name: 'navbar-nav', module: NavbarModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'drawer',
    description: 'Slide-out navigation drawer for mobile interfaces',
    tags: ['navigation', 'drawer', 'mobile'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-drawer-nav',
  template: \`<button class="toggle" (click)="open=true">\\u2630</button><div class="overlay" *ngIf="open"><div class="backdrop" (click)="open=false"></div><nav class="drawer"><button class="close" (click)="open=false">\\u2715</button><a *ngFor="let item of items" href="#" (click)="open=false">{{ item }}</a></nav></div>\`,
  styles: [\`.toggle { padding: 10px 16px; background: #fff; border: 1px solid #d1d5db; border-radius: 6px; cursor: pointer; font-size: 20px; } .overlay { position: fixed; inset: 0; z-index: 50; display: flex; } .backdrop { position: absolute; inset: 0; background: rgba(0,0,0,0.4); } .drawer { position: relative; width: 260px; background: #fff; padding: 20px; display: flex; flex-direction: column; gap: 4px; } .close { align-self: flex-end; background: none; border: none; font-size: 18px; cursor: pointer; margin-bottom: 16px; } .drawer a { padding: 12px 8px; text-decoration: none; color: #374151; font-size: 15px; border-radius: 6px; } .drawer a:hover { background: #f3f4f6; }\`]
})
export class DrawerNavComponent { open = false; items = ['Home', 'Explore', 'Notifications', 'Messages', 'Profile']; }

@NgModule({ declarations: [DrawerNavComponent], imports: [BrowserModule], bootstrap: [DrawerNavComponent] })
export class DrawerNavModule {}
export default createAngularMicroApp({ name: 'drawer-nav', module: DrawerNavModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'mega-menu',
    description: 'Mega menu navigation with multi-column dropdown',
    tags: ['navigation', 'mega-menu', 'complex'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-mega-menu',
  template: \`<nav class="nav"><div class="menu-trigger" (mouseenter)="open=true" (mouseleave)="open=false"><button class="nav-btn">Products \\u25BC</button><div class="mega" *ngIf="open"><div class="col" *ngFor="let col of columns"><h4 class="col-title">{{ col.title }}</h4><a *ngFor="let link of col.links" href="#" class="mega-link">{{ link }}</a></div></div></div></nav>\`,
  styles: [\`.nav { position: relative; } .nav-btn { padding: 10px 20px; background: none; border: none; font-size: 14px; font-weight: 600; cursor: pointer; } .mega { position: absolute; top: 100%; left: 0; background: #fff; border: 1px solid #e5e7eb; border-radius: 12px; padding: 24px; display: flex; gap: 32px; box-shadow: 0 8px 24px rgba(0,0,0,0.1); z-index: 20; } .col-title { font-size: 12px; font-weight: 700; text-transform: uppercase; color: #9ca3af; margin: 0 0 8px; } .mega-link { display: block; padding: 4px 0; font-size: 14px; color: #374151; text-decoration: none; } .mega-link:hover { color: #6366f1; }\`]
})
export class MegaMenuComponent {
  open = false;
  columns = [
    { title: 'Platform', links: ['Overview', 'Features', 'Integrations'] },
    { title: 'Solutions', links: ['Enterprise', 'Small Business', 'Startups'] },
    { title: 'Resources', links: ['Documentation', 'Tutorials', 'Community'] },
  ];
}

@NgModule({ declarations: [MegaMenuComponent], imports: [BrowserModule], bootstrap: [MegaMenuComponent] })
export class MegaMenuModule {}
export default createAngularMicroApp({ name: 'mega-menu-nav', module: MegaMenuModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'bottom-bar',
    description: 'Bottom navigation bar for mobile app interfaces',
    tags: ['navigation', 'bottom-bar', 'mobile'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-bottom-bar',
  template: \`<nav class="bottom-bar"><button *ngFor="let item of items" class="bar-item" [class.active]="active===item.label" (click)="active=item.label"><span class="icon">{{ item.icon }}</span><span class="label">{{ item.label }}</span></button></nav>\`,
  styles: [\`.bottom-bar { position: fixed; bottom: 0; left: 0; right: 0; display: flex; background: #fff; border-top: 1px solid #e5e7eb; padding: 8px 0 12px; } .bar-item { flex: 1; display: flex; flex-direction: column; align-items: center; gap: 2px; background: none; border: none; cursor: pointer; padding: 4px; } .icon { font-size: 20px; } .label { font-size: 11px; color: #6b7280; } .bar-item.active .label { color: #6366f1; font-weight: 600; }\`]
})
export class BottomBarComponent {
  active = 'Home';
  items = [{ icon: '\\u{1F3E0}', label: 'Home' }, { icon: '\\u{1F50D}', label: 'Search' }, { icon: '\\u{2795}', label: 'Create' }, { icon: '\\u{1F514}', label: 'Alerts' }, { icon: '\\u{1F464}', label: 'Profile' }];
}

@NgModule({ declarations: [BottomBarComponent], imports: [BrowserModule], bootstrap: [BottomBarComponent] })
export class BottomBarModule {}
export default createAngularMicroApp({ name: 'bottom-bar-nav', module: BottomBarModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'side-menu',
    description: 'Vertical side menu with grouped navigation items',
    tags: ['navigation', 'side-menu', 'vertical'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-side-menu',
  template: \`<nav class="side-menu"><div *ngFor="let group of groups" class="group"><div class="group-title">{{ group.title }}</div><a *ngFor="let item of group.items" href="#" class="menu-item" [class.active]="active===item" (click)="active=item">{{ item }}</a></div></nav>\`,
  styles: [\`.side-menu { width: 220px; padding: 16px 0; } .group { margin-bottom: 20px; } .group-title { font-size: 11px; font-weight: 700; text-transform: uppercase; color: #9ca3af; padding: 0 16px 8px; letter-spacing: 0.05em; } .menu-item { display: block; padding: 8px 16px; text-decoration: none; color: #374151; font-size: 14px; border-radius: 6px; margin: 0 8px; } .menu-item:hover { background: #f3f4f6; } .menu-item.active { background: #ede9fe; color: #6366f1; font-weight: 600; }\`]
})
export class SideMenuComponent {
  active = 'Dashboard';
  groups = [
    { title: 'Main', items: ['Dashboard', 'Projects', 'Tasks'] },
    { title: 'Team', items: ['Members', 'Roles', 'Activity'] },
    { title: 'Account', items: ['Settings', 'Billing'] },
  ];
}

@NgModule({ declarations: [SideMenuComponent], imports: [BrowserModule], bootstrap: [SideMenuComponent] })
export class SideMenuModule {}
export default createAngularMicroApp({ name: 'side-menu-nav', module: SideMenuModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'wizard',
    description: 'Wizard navigation with connected step indicators',
    tags: ['navigation', 'wizard', 'steps'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-wizard-nav',
  template: \`<div class="wizard"><div *ngFor="let step of steps; let i = index" class="step-item"><div class="connector" *ngIf="i > 0" [class.filled]="i <= current"></div><div class="step-circle" [class.active]="i === current" [class.done]="i < current" (click)="current=i">{{ i < current ? '\\u2713' : i + 1 }}</div><div class="step-label" [class.active]="i === current">{{ step }}</div></div></div>\`,
  styles: [\`.wizard { display: flex; align-items: flex-start; padding: 20px 0; } .step-item { display: flex; flex-direction: column; align-items: center; position: relative; flex: 1; } .connector { position: absolute; top: 16px; right: 50%; width: 100%; height: 2px; background: #e5e7eb; z-index: 0; } .connector.filled { background: #6366f1; } .step-circle { width: 32px; height: 32px; border-radius: 50%; border: 2px solid #d1d5db; display: flex; align-items: center; justify-content: center; font-size: 13px; font-weight: 600; background: #fff; z-index: 1; cursor: pointer; } .step-circle.active { border-color: #6366f1; color: #6366f1; } .step-circle.done { background: #6366f1; color: #fff; border-color: #6366f1; } .step-label { font-size: 12px; color: #6b7280; margin-top: 8px; } .step-label.active { color: #6366f1; font-weight: 600; }\`]
})
export class WizardNavComponent { current = 1; steps = ['Cart', 'Shipping', 'Payment', 'Review']; }

@NgModule({ declarations: [WizardNavComponent], imports: [BrowserModule], bootstrap: [WizardNavComponent] })
export class WizardNavModule {}
export default createAngularMicroApp({ name: 'wizard-nav', module: WizardNavModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'segmented-control',
    description: 'Segmented control for switching between views',
    tags: ['navigation', 'segmented', 'toggle'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-segmented-control',
  template: \`<div class="control"><button *ngFor="let seg of segments" class="segment" [class.active]="active===seg" (click)="active=seg">{{ seg }}</button></div><div class="content">Showing: {{ active }}</div>\`,
  styles: [\`.control { display: inline-flex; background: #f3f4f6; border-radius: 8px; padding: 4px; } .segment { padding: 8px 20px; border: none; background: transparent; border-radius: 6px; cursor: pointer; font-size: 14px; font-weight: 500; color: #6b7280; } .segment.active { background: #fff; color: #374151; box-shadow: 0 1px 3px rgba(0,0,0,0.1); font-weight: 600; } .content { padding: 16px 0; font-size: 14px; color: #6b7280; }\`]
})
export class SegmentedControlComponent { active = 'Grid'; segments = ['Grid', 'List', 'Board']; }

@NgModule({ declarations: [SegmentedControlComponent], imports: [BrowserModule], bootstrap: [SegmentedControlComponent] })
export class SegmentedControlModule {}
export default createAngularMicroApp({ name: 'segmented-control-nav', module: SegmentedControlModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'anchor-nav',
    description: 'Anchor navigation for scrolling to page sections',
    tags: ['navigation', 'anchor', 'scroll'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-anchor-nav',
  template: \`<nav class="anchor-nav"><a *ngFor="let section of sections" [href]="'#' + section.toLowerCase()" class="anchor" [class.active]="active===section" (click)="active=section">{{ section }}</a></nav>\`,
  styles: [\`.anchor-nav { display: flex; flex-direction: column; gap: 2px; width: 180px; border-left: 2px solid #e5e7eb; padding-left: 12px; } .anchor { padding: 6px 12px; text-decoration: none; color: #6b7280; font-size: 13px; border-radius: 4px; } .anchor:hover { color: #374151; } .anchor.active { color: #6366f1; font-weight: 600; background: #ede9fe; }\`]
})
export class AnchorNavComponent { active = 'Introduction'; sections = ['Introduction', 'Installation', 'Usage', 'API', 'Examples', 'FAQ']; }

@NgModule({ declarations: [AnchorNavComponent], imports: [BrowserModule], bootstrap: [AnchorNavComponent] })
export class AnchorNavModule {}
export default createAngularMicroApp({ name: 'anchor-nav', module: AnchorNavModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'tag-nav',
    description: 'Tag-based navigation for filtering content by tags',
    tags: ['navigation', 'tags', 'filter'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-tag-nav',
  template: \`<div class="tags"><button *ngFor="let tag of tags" class="tag" [class.active]="selected.includes(tag)" (click)="toggle(tag)">{{ tag }}</button></div><div class="info">Selected: {{ selected.length ? selected.join(', ') : 'None' }}</div>\`,
  styles: [\`.tags { display: flex; flex-wrap: wrap; gap: 8px; padding: 12px 0; } .tag { padding: 6px 14px; border: 1px solid #d1d5db; border-radius: 20px; background: #fff; cursor: pointer; font-size: 13px; color: #374151; } .tag:hover { border-color: #6366f1; } .tag.active { background: #6366f1; color: #fff; border-color: #6366f1; } .info { font-size: 13px; color: #6b7280; padding: 8px 0; }\`]
})
export class TagNavComponent {
  selected: string[] = [];
  tags = ['All', 'Angular', 'React', 'Vue', 'Svelte', 'TypeScript', 'CSS'];
  toggle(tag: string) { const i = this.selected.indexOf(tag); if (i >= 0) this.selected.splice(i, 1); else this.selected.push(tag); }
}

@NgModule({ declarations: [TagNavComponent], imports: [BrowserModule], bootstrap: [TagNavComponent] })
export class TagNavModule {}
export default createAngularMicroApp({ name: 'tag-nav', module: TagNavModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
  {
    variant: 'dot-nav',
    description: 'Dot indicator navigation for carousels and slideshows',
    tags: ['navigation', 'dots', 'carousel'],
    code: `import { Component } from '@angular/core';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { createAngularMicroApp } from '@tuvix.js/angular';

@Component({
  selector: 'app-dot-nav',
  template: \`<div class="slide" [style.background]="slides[current].color"><div class="slide-text">{{ slides[current].label }}</div></div><div class="dots"><button class="arrow" (click)="prev()">\\u2190</button><button *ngFor="let s of slides; let i = index" class="dot" [class.active]="i===current" (click)="current=i"></button><button class="arrow" (click)="next()">\\u2192</button></div>\`,
  styles: [\`.slide { height: 200px; border-radius: 12px; display: flex; align-items: center; justify-content: center; margin-bottom: 12px; } .slide-text { color: #fff; font-size: 20px; font-weight: 700; text-shadow: 0 1px 3px rgba(0,0,0,0.3); } .dots { display: flex; align-items: center; justify-content: center; gap: 8px; } .dot { width: 10px; height: 10px; border-radius: 50%; border: none; background: #d1d5db; cursor: pointer; padding: 0; } .dot.active { background: #6366f1; width: 24px; border-radius: 5px; } .arrow { background: none; border: none; font-size: 18px; cursor: pointer; padding: 4px 8px; }\`]
})
export class DotNavComponent {
  current = 0;
  slides = [
    { label: 'Slide 1', color: 'linear-gradient(135deg, #a78bfa, #6366f1)' },
    { label: 'Slide 2', color: 'linear-gradient(135deg, #34d399, #10b981)' },
    { label: 'Slide 3', color: 'linear-gradient(135deg, #fbbf24, #f59e0b)' },
    { label: 'Slide 4', color: 'linear-gradient(135deg, #f87171, #ef4444)' },
  ];
  prev() { this.current = (this.current - 1 + this.slides.length) % this.slides.length; }
  next() { this.current = (this.current + 1) % this.slides.length; }
}

@NgModule({ declarations: [DotNavComponent], imports: [BrowserModule], bootstrap: [DotNavComponent] })
export class DotNavModule {}
export default createAngularMicroApp({ name: 'dot-nav', module: DotNavModule, platform: platformBrowserDynamic });`,
    dependencies: ['@tuvix.js/angular', '@tuvix.js/core', '@angular/core', '@angular/platform-browser', '@angular/platform-browser-dynamic'],
  },
];

export default templates;

// chatbot/scripts/templates/react/navigation.ts
import type { ComponentTemplate } from '../../generate-dataset';

const templates: ComponentTemplate[] = [
  {
    variant: 'breadcrumb',
    description: 'Breadcrumb navigation with separator icons',
    tags: ['navigation', 'breadcrumb', 'trail'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React from 'react';

function BreadcrumbNav() {
  const crumbs = [{ label: 'Home', href: '#home' }, { label: 'Products', href: '#products' }, { label: 'Widgets', href: '#widgets' }, { label: 'Pro Model' }];
  return (
    <nav style={{ padding: '12px 0', fontSize: '14px' }}>
      {crumbs.map((crumb, i) => (
        <span key={crumb.label}>
          {i > 0 && <span style={{ margin: '0 8px', color: '#9ca3af' }}>/</span>}
          {crumb.href ? <a href={crumb.href} style={{ color: '#6366f1', textDecoration: 'none' }}>{crumb.label}</a> : <span style={{ color: '#6b7280' }}>{crumb.label}</span>}
        </span>
      ))}
    </nav>
  );
}
export default createReactMicroApp({ name: 'breadcrumb-nav', App: BreadcrumbNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'tabs',
    description: 'Tab navigation with underline active indicator',
    tags: ['navigation', 'tabs', 'panel'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function TabsNav() {
  const tabs = ['Overview', 'Features', 'Pricing', 'FAQ'];
  const [active, setActive] = useState('Overview');
  return (
    <div>
      <div style={{ display: 'flex', borderBottom: '2px solid #e5e7eb' }}>
        {tabs.map((tab) => (
          <button key={tab} onClick={() => setActive(tab)} style={{ padding: '12px 20px', border: 'none', borderBottom: active === tab ? '2px solid #6366f1' : '2px solid transparent', marginBottom: '-2px', background: 'none', cursor: 'pointer', fontWeight: active === tab ? 600 : 400, color: active === tab ? '#6366f1' : '#6b7280', fontSize: '14px' }}>{tab}</button>
        ))}
      </div>
      <div style={{ padding: '20px 0', fontSize: '14px', color: '#374151' }}>Content for: {active}</div>
    </div>
  );
}
export default createReactMicroApp({ name: 'tabs-nav', App: TabsNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'stepper',
    description: 'Step-by-step progress navigation with numbered steps',
    tags: ['navigation', 'stepper', 'progress'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function StepperNav() {
  const steps = ['Account', 'Profile', 'Preferences', 'Review'];
  const [current, setCurrent] = useState(1);
  return (
    <div style={{ padding: '20px' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', marginBottom: '24px' }}>
        {steps.map((step, i) => (
          <React.Fragment key={step}>
            {i > 0 && <div style={{ width: '40px', height: '2px', backgroundColor: i <= current ? '#6366f1' : '#e5e7eb' }} />}
            <div onClick={() => setCurrent(i)} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', cursor: 'pointer', gap: '4px' }}>
              <div style={{ width: '32px', height: '32px', borderRadius: '50%', backgroundColor: i <= current ? '#6366f1' : '#e5e7eb', color: i <= current ? '#fff' : '#9ca3af', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '14px', fontWeight: 600 }}>{i < current ? '\\u2713' : i + 1}</div>
              <span style={{ fontSize: '12px', color: i <= current ? '#6366f1' : '#9ca3af' }}>{step}</span>
            </div>
          </React.Fragment>
        ))}
      </div>
      <div style={{ textAlign: 'center', fontSize: '14px', color: '#374151' }}>Step {current + 1}: {steps[current]}</div>
    </div>
  );
}
export default createReactMicroApp({ name: 'stepper-nav', App: StepperNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'pagination',
    description: 'Pagination navigation with page numbers and prev/next',
    tags: ['navigation', 'pagination', 'pages'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function PaginationNav() {
  const totalPages = 10;
  const [page, setPage] = useState(1);
  const range = Array.from({ length: Math.min(5, totalPages) }).map((_, i) => {
    const start = Math.max(1, Math.min(page - 2, totalPages - 4));
    return start + i;
  });
  return (
    <nav style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
      <button onClick={() => setPage(Math.max(1, page - 1))} disabled={page === 1} style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: '6px', backgroundColor: '#fff', cursor: page === 1 ? 'default' : 'pointer', opacity: page === 1 ? 0.5 : 1 }}>Prev</button>
      {range.map((p) => (
        <button key={p} onClick={() => setPage(p)} style={{ width: '36px', height: '36px', border: 'none', borderRadius: '6px', backgroundColor: p === page ? '#6366f1' : 'transparent', color: p === page ? '#fff' : '#374151', cursor: 'pointer', fontWeight: 600, fontSize: '14px' }}>{p}</button>
      ))}
      <button onClick={() => setPage(Math.min(totalPages, page + 1))} disabled={page === totalPages} style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: '6px', backgroundColor: '#fff', cursor: page === totalPages ? 'default' : 'pointer', opacity: page === totalPages ? 0.5 : 1 }}>Next</button>
    </nav>
  );
}
export default createReactMicroApp({ name: 'pagination-nav', App: PaginationNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'menu',
    description: 'Dropdown context menu with nested items',
    tags: ['navigation', 'menu', 'dropdown'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function MenuNav() {
  const [open, setOpen] = useState(false);
  const items = ['New File', 'Open...', 'Save', 'Save As...', 'Export', 'Close'];
  return (
    <div style={{ position: 'relative', display: 'inline-block' }}>
      <button onClick={() => setOpen(!open)} style={{ padding: '8px 16px', border: '1px solid #d1d5db', borderRadius: '6px', backgroundColor: '#fff', cursor: 'pointer', fontSize: '14px' }}>File \\u25BC</button>
      {open && (
        <div style={{ position: 'absolute', top: '100%', left: 0, marginTop: '4px', backgroundColor: '#fff', border: '1px solid #e5e7eb', borderRadius: '8px', boxShadow: '0 4px 12px rgba(0,0,0,0.1)', minWidth: '160px', zIndex: 10, padding: '4px 0' }}>
          {items.map((item, i) => (
            <button key={item} onClick={() => setOpen(false)} style={{ display: 'block', width: '100%', textAlign: 'left', padding: '8px 16px', border: 'none', background: 'none', cursor: 'pointer', fontSize: '14px', color: '#374151', borderTop: i === 4 ? '1px solid #e5e7eb' : 'none' }}>{item}</button>
          ))}
        </div>
      )}
    </div>
  );
}
export default createReactMicroApp({ name: 'menu-nav', App: MenuNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'navbar',
    description: 'Horizontal navbar with logo and nav links',
    tags: ['navigation', 'navbar', 'horizontal'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function NavbarNav() {
  const [active, setActive] = useState('home');
  const links = ['Home', 'Products', 'About', 'Blog', 'Contact'];
  return (
    <nav style={{ display: 'flex', alignItems: 'center', padding: '12px 24px', backgroundColor: '#fff', borderBottom: '1px solid #e5e7eb' }}>
      <span style={{ fontSize: '18px', fontWeight: 700, marginRight: '32px' }}>Brand</span>
      {links.map((link) => {
        const key = link.toLowerCase();
        return <a key={key} href={'#' + key} onClick={() => setActive(key)} style={{ padding: '8px 14px', textDecoration: 'none', color: active === key ? '#6366f1' : '#6b7280', fontWeight: active === key ? 600 : 400, fontSize: '14px', borderRadius: '6px', backgroundColor: active === key ? '#ede9fe' : 'transparent' }}>{link}</a>;
      })}
    </nav>
  );
}
export default createReactMicroApp({ name: 'navbar-nav', App: NavbarNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'drawer',
    description: 'Navigation drawer that slides in from the side',
    tags: ['navigation', 'drawer', 'mobile'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function DrawerNav() {
  const [open, setOpen] = useState(false);
  const links = ['Dashboard', 'Profile', 'Settings', 'Help', 'Logout'];
  return (
    <>
      <button onClick={() => setOpen(true)} style={{ padding: '10px 16px', border: 'none', borderRadius: '6px', backgroundColor: '#111827', color: '#fff', cursor: 'pointer', fontSize: '16px' }}>\\u2630 Menu</button>
      {open && (
        <div style={{ position: 'fixed', inset: 0, zIndex: 100, display: 'flex' }}>
          <nav style={{ width: '260px', backgroundColor: '#fff', boxShadow: '4px 0 16px rgba(0,0,0,0.1)', padding: '24px 16px', display: 'flex', flexDirection: 'column' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
              <span style={{ fontWeight: 700, fontSize: '18px' }}>Navigation</span>
              <button onClick={() => setOpen(false)} style={{ background: 'none', border: 'none', fontSize: '20px', cursor: 'pointer' }}>\\u2715</button>
            </div>
            {links.map((link) => (
              <a key={link} href={'#' + link.toLowerCase()} onClick={() => setOpen(false)} style={{ padding: '12px 8px', textDecoration: 'none', color: link === 'Logout' ? '#ef4444' : '#374151', fontSize: '15px', borderRadius: '6px' }}>{link}</a>
            ))}
          </nav>
          <div onClick={() => setOpen(false)} style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.3)' }} />
        </div>
      )}
    </>
  );
}
export default createReactMicroApp({ name: 'drawer-nav', App: DrawerNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'mega-menu',
    description: 'Mega menu with multiple columns of categorized links',
    tags: ['navigation', 'mega-menu', 'enterprise'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function MegaMenuNav() {
  const [open, setOpen] = useState(false);
  const columns: Record<string, string[]> = {
    Products: ['Widget Pro', 'Widget Lite', 'Enterprise Suite'],
    Solutions: ['Startups', 'Agencies', 'Enterprise'],
    Resources: ['Documentation', 'Blog', 'Community'],
  };
  return (
    <nav style={{ position: 'relative', backgroundColor: '#fff', borderBottom: '1px solid #e5e7eb' }}>
      <div style={{ display: 'flex', alignItems: 'center', padding: '12px 24px', gap: '24px' }}>
        <span style={{ fontSize: '18px', fontWeight: 700 }}>Corp</span>
        <button onMouseEnter={() => setOpen(true)} onMouseLeave={() => setOpen(false)} style={{ padding: '8px 12px', border: 'none', background: 'none', cursor: 'pointer', fontSize: '14px', fontWeight: 500 }}>Products \\u25BC</button>
        <a href="#pricing" style={{ textDecoration: 'none', color: '#374151', fontSize: '14px' }}>Pricing</a>
      </div>
      {open && (
        <div onMouseEnter={() => setOpen(true)} onMouseLeave={() => setOpen(false)} style={{ position: 'absolute', top: '100%', left: 0, right: 0, backgroundColor: '#fff', borderTop: '1px solid #e5e7eb', boxShadow: '0 8px 24px rgba(0,0,0,0.1)', padding: '24px 32px', display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '32px', zIndex: 20 }}>
          {Object.entries(columns).map(([title, links]) => (
            <div key={title}>
              <h4 style={{ fontSize: '14px', fontWeight: 700, margin: '0 0 8px', color: '#111827' }}>{title}</h4>
              {links.map((l) => <a key={l} href="#" style={{ display: 'block', padding: '6px 0', textDecoration: 'none', color: '#6b7280', fontSize: '14px' }}>{l}</a>)}
            </div>
          ))}
        </div>
      )}
    </nav>
  );
}
export default createReactMicroApp({ name: 'mega-menu-nav', App: MegaMenuNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'bottom-bar',
    description: 'Mobile bottom navigation bar with icon buttons',
    tags: ['navigation', 'bottom-bar', 'mobile'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function BottomBarNav() {
  const [active, setActive] = useState('home');
  const items = [
    { id: 'home', icon: '\\u2302', label: 'Home' },
    { id: 'search', icon: '\\u2315', label: 'Search' },
    { id: 'add', icon: '\\u271A', label: 'Create' },
    { id: 'notifications', icon: '\\u2709', label: 'Alerts' },
    { id: 'profile', icon: '\\u263A', label: 'Profile' },
  ];
  return (
    <nav style={{ position: 'fixed', bottom: 0, left: 0, right: 0, display: 'flex', backgroundColor: '#fff', borderTop: '1px solid #e5e7eb', padding: '6px 0' }}>
      {items.map((item) => (
        <button key={item.id} onClick={() => setActive(item.id)} style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '2px', padding: '6px 0', border: 'none', backgroundColor: 'transparent', cursor: 'pointer', color: active === item.id ? '#6366f1' : '#9ca3af' }}>
          <span style={{ fontSize: '20px' }}>{item.icon}</span>
          <span style={{ fontSize: '11px', fontWeight: active === item.id ? 600 : 400 }}>{item.label}</span>
        </button>
      ))}
    </nav>
  );
}
export default createReactMicroApp({ name: 'bottom-bar-nav', App: BottomBarNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'side-menu',
    description: 'Vertical side menu with active state highlighting',
    tags: ['navigation', 'side-menu', 'vertical'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function SideMenuNav() {
  const [active, setActive] = useState('overview');
  const items = ['Overview', 'Accounts', 'Transactions', 'Reports', 'Settings'];
  return (
    <nav style={{ width: '200px', padding: '16px 8px' }}>
      {items.map((item) => {
        const key = item.toLowerCase();
        return (
          <button key={key} onClick={() => setActive(key)} style={{ display: 'block', width: '100%', textAlign: 'left', padding: '10px 12px', border: 'none', borderRadius: '6px', backgroundColor: active === key ? '#ede9fe' : 'transparent', color: active === key ? '#6366f1' : '#374151', cursor: 'pointer', fontSize: '14px', fontWeight: active === key ? 600 : 400, marginBottom: '2px' }}>{item}</button>
        );
      })}
    </nav>
  );
}
export default createReactMicroApp({ name: 'side-menu-nav', App: SideMenuNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'wizard',
    description: 'Wizard navigation with labeled steps and completion status',
    tags: ['navigation', 'wizard', 'multi-step'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function WizardNav() {
  const steps = ['Select Plan', 'Account Details', 'Payment', 'Confirmation'];
  const [current, setCurrent] = useState(0);
  return (
    <div style={{ padding: '24px' }}>
      <div style={{ display: 'flex', marginBottom: '32px' }}>
        {steps.map((step, i) => (
          <div key={step} style={{ flex: 1, textAlign: 'center', position: 'relative' }}>
            {i > 0 && <div style={{ position: 'absolute', top: '14px', left: '-50%', right: '50%', height: '2px', backgroundColor: i <= current ? '#6366f1' : '#e5e7eb' }} />}
            <div onClick={() => i < current && setCurrent(i)} style={{ width: '28px', height: '28px', borderRadius: '50%', backgroundColor: i < current ? '#10b981' : i === current ? '#6366f1' : '#e5e7eb', color: i <= current ? '#fff' : '#9ca3af', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: '12px', fontWeight: 700, cursor: i < current ? 'pointer' : 'default', position: 'relative', zIndex: 1 }}>{i < current ? '\\u2713' : i + 1}</div>
            <div style={{ fontSize: '12px', marginTop: '6px', color: i <= current ? '#374151' : '#9ca3af' }}>{step}</div>
          </div>
        ))}
      </div>
      <div style={{ display: 'flex', justifyContent: 'space-between' }}>
        <button onClick={() => setCurrent(Math.max(0, current - 1))} disabled={current === 0} style={{ padding: '8px 20px', border: '1px solid #d1d5db', borderRadius: '6px', background: '#fff', cursor: current === 0 ? 'default' : 'pointer', opacity: current === 0 ? 0.4 : 1 }}>Back</button>
        <button onClick={() => setCurrent(Math.min(steps.length - 1, current + 1))} style={{ padding: '8px 20px', border: 'none', borderRadius: '6px', backgroundColor: '#6366f1', color: '#fff', cursor: 'pointer', fontWeight: 600 }}>{current === steps.length - 1 ? 'Finish' : 'Next'}</button>
      </div>
    </div>
  );
}
export default createReactMicroApp({ name: 'wizard-nav', App: WizardNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'segmented-control',
    description: 'Segmented control for switching between views',
    tags: ['navigation', 'segmented', 'toggle'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function SegmentedControlNav() {
  const options = ['Day', 'Week', 'Month', 'Year'];
  const [selected, setSelected] = useState('Week');
  return (
    <div style={{ display: 'inline-flex', backgroundColor: '#f3f4f6', borderRadius: '8px', padding: '3px' }}>
      {options.map((opt) => (
        <button key={opt} onClick={() => setSelected(opt)} style={{ padding: '8px 20px', border: 'none', borderRadius: '6px', backgroundColor: selected === opt ? '#fff' : 'transparent', color: selected === opt ? '#111827' : '#6b7280', cursor: 'pointer', fontWeight: selected === opt ? 600 : 400, fontSize: '14px', boxShadow: selected === opt ? '0 1px 3px rgba(0,0,0,0.1)' : 'none', transition: 'all 0.15s' }}>{opt}</button>
      ))}
    </div>
  );
}
export default createReactMicroApp({ name: 'segmented-control-nav', App: SegmentedControlNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'anchor-nav',
    description: 'Anchor navigation that scrolls to page sections',
    tags: ['navigation', 'anchor', 'scroll'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function AnchorNav() {
  const [active, setActive] = useState('intro');
  const sections = ['Introduction', 'Features', 'Pricing', 'FAQ', 'Contact'];
  return (
    <nav style={{ position: 'sticky', top: 0, backgroundColor: '#fff', borderBottom: '1px solid #e5e7eb', padding: '0 24px', zIndex: 10 }}>
      <div style={{ display: 'flex', gap: '4px', maxWidth: '800px', margin: '0 auto' }}>
        {sections.map((section) => {
          const key = section.toLowerCase();
          return (
            <a key={key} href={'#' + key} onClick={() => setActive(key)} style={{ padding: '14px 16px', textDecoration: 'none', color: active === key ? '#6366f1' : '#6b7280', borderBottom: active === key ? '2px solid #6366f1' : '2px solid transparent', fontSize: '14px', fontWeight: active === key ? 600 : 400 }}>{section}</a>
          );
        })}
      </div>
    </nav>
  );
}
export default createReactMicroApp({ name: 'anchor-nav', App: AnchorNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'tag-nav',
    description: 'Tag-based navigation with toggleable filter chips',
    tags: ['navigation', 'tags', 'filter'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function TagNav() {
  const allTags = ['React', 'Vue', 'Svelte', 'Angular', 'TypeScript', 'JavaScript', 'CSS', 'Node.js'];
  const [selected, setSelected] = useState<Set<string>>(new Set(['React']));
  const toggle = (tag: string) => { const s = new Set(selected); if (s.has(tag)) s.delete(tag); else s.add(tag); setSelected(s); };
  return (
    <div>
      <div style={{ fontSize: '14px', color: '#6b7280', marginBottom: '8px' }}>Filter by tag:</div>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
        {allTags.map((tag) => (
          <button key={tag} onClick={() => toggle(tag)} style={{ padding: '6px 14px', borderRadius: '16px', border: selected.has(tag) ? '2px solid #6366f1' : '1px solid #d1d5db', backgroundColor: selected.has(tag) ? '#ede9fe' : '#fff', color: selected.has(tag) ? '#6366f1' : '#374151', cursor: 'pointer', fontSize: '13px', fontWeight: selected.has(tag) ? 600 : 400 }}>{tag}</button>
        ))}
      </div>
      <div style={{ marginTop: '12px', fontSize: '13px', color: '#9ca3af' }}>{selected.size} tag{selected.size !== 1 ? 's' : ''} selected</div>
    </div>
  );
}
export default createReactMicroApp({ name: 'tag-nav', App: TagNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
  {
    variant: 'dot-nav',
    description: 'Dot navigation for carousel/slideshow indicators',
    tags: ['navigation', 'dots', 'carousel'],
    code: `import { createReactMicroApp } from '@tuvix.js/react';
import React, { useState } from 'react';

function DotNav() {
  const total = 7;
  const [active, setActive] = useState(0);
  return (
    <div style={{ padding: '20px', textAlign: 'center' }}>
      <div style={{ padding: '40px', backgroundColor: '#f9fafb', borderRadius: '10px', marginBottom: '16px', fontSize: '18px', fontWeight: 600, color: '#374151' }}>Slide {active + 1} of {total}</div>
      <div style={{ display: 'flex', justifyContent: 'center', gap: '8px', alignItems: 'center' }}>
        <button onClick={() => setActive(Math.max(0, active - 1))} style={{ background: 'none', border: 'none', fontSize: '18px', cursor: 'pointer', color: '#6b7280' }}>\\u25C0</button>
        {Array.from({ length: total }).map((_, i) => (
          <button key={i} onClick={() => setActive(i)} style={{ width: active === i ? '24px' : '10px', height: '10px', borderRadius: '5px', border: 'none', backgroundColor: active === i ? '#6366f1' : '#d1d5db', cursor: 'pointer', transition: 'width 0.2s', padding: 0 }} />
        ))}
        <button onClick={() => setActive(Math.min(total - 1, active + 1))} style={{ background: 'none', border: 'none', fontSize: '18px', cursor: 'pointer', color: '#6b7280' }}>\\u25B6</button>
      </div>
    </div>
  );
}
export default createReactMicroApp({ name: 'dot-nav', App: DotNav });`,
    dependencies: ['@tuvix.js/react', '@tuvix.js/core'],
  },
];

export default templates;
